#!/usr/bin/env python3
"""Structurally match Mickey's 107 overlays to Jet Force Gemini's 157 modules.

Byte-identity between the two games' overlay code found only three shared
functions (docs/acceleration-survey.md section 6): `alSeqFileNew`,
`refractOutput`, and `osRamTest4_6105`/`osRamTest3_6105`. JFG's overlay code
was compiled from a different revision, so bytes mostly do not match. What
does transfer is *structure*: each overlay's text/data/bss footprint,
function-count profile, and cross-overlay call graph. Mickey's atlas
(``config/overlays.us.json``) already carries all of that for Mickey's 107
modules; JFG publishes the equivalent facts about its own 157 modules in its
own decomp repo (``jfg_us_syms_full.txt``, ``overly_refs.txt``, and the build
map). Neither input is ROM-derived: Mickey's side is metadata already
generated by ``overlay_atlas.py`` (sizes, counts, offsets -- never
disassembly), and JFG's side is JFG's own published decomp source and build
artifacts, a permitted source under docs/CLEANROOM.md.

This tool builds one feature vector per module on each side, scores every
Mickey-overlay/JFG-module pair by a blend of cosine similarity over
size/count features and a Jaccar-like overlap of resident-import and
cross-overlay-neighbour "shape", and reports the top-3 JFG candidates for
each Mickey overlay. It also runs a calibration self-test: the known
byte-identical anchors, plus JFG-US-vs-JFG-kiosk (which is truly the same
game, so the recovery rate there upper-bounds what this method can do on a
harder cross-game problem).

No ROM bytes, instruction text, or hexdumps are read or written anywhere in
this tool. Every JFG fact used here is a published symbol name/offset or a
build-map section size, and every Mickey fact comes from the existing atlas.

Usage:
    tools/overlay_graph_match.py                  # concise summary
    tools/overlay_graph_match.py --write           # refresh config/overlay-graph.us.json
    tools/overlay_graph_match.py --check           # fail if the report is stale
    tools/overlay_graph_match.py --self-test       # JFG-us vs JFG-kiosk calibration only
    tools/overlay_graph_match.py --overlay 61      # one Mickey overlay's candidates
"""

import argparse
import json
import math
import os
import re
import sys
from collections import defaultdict

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ATLAS = os.path.join(REPO, "config", "overlays.us.json")
REPORT = os.path.join(REPO, "config", "overlay-graph.us.json")

JFG_ROOT = os.path.expanduser(
    os.environ.get("JFG_ROOT", "~/Desktop/dev/decomp-refs/jfg")
)
JFG_SYMS_US = os.path.join(JFG_ROOT, "jfg_us_syms_full.txt")
JFG_SYMS_KIOSK = os.path.join(JFG_ROOT, "jfg_kiosk_syms_full.txt")
JFG_REFS = os.path.join(JFG_ROOT, "overly_refs.txt")
JFG_MAP = os.path.join(JFG_ROOT, "build", "jfg.us.map")

# The three byte-identical cross-game anchors (docs/acceleration-survey.md
# section 6). Only two land inside a JFG *overlay module* -- alSeqFileNew is
# JFG resident/library audio code with no module section of its own, so it
# cannot anchor a module-to-module pair and is reported but not scored.
KNOWN_ANCHORS = {
    # Mickey overlay -> JFG module, by the shared byte-identical symbol.
    49: {"jfg_module": 2, "symbol": "refractOutput"},
    107: {"jfg_module": 156, "symbol": "osRamTest4_6105"},
}
UNANCHORABLE = {"alSeqFileNew": "resident in JFG, not module-scoped"}

AUTOEXIT_RE = re.compile(r"^_AutoExit\d+$")
SECTION_RE = re.compile(
    r"^=== Section 0x([0-9A-Fa-f]+): (Main Code|Data \(FFD\)|BSS|Module (\d+)) "
    r"\((\d+) symbols\) ==="
)
SYM_RE = re.compile(r"^\s*\+0x([0-9A-Fa-f]+)\s+(\S+)")
MAIN_SYM_RE = re.compile(r"^\s*([0-9A-Fa-f]{8})\s+(\S+)")

MAP_OBJ_RE = re.compile(
    r"^\s*\.(text|data|rodata|bss)\s+0x([0-9a-fA-F]+)\s+0x([0-9a-fA-F]+)\s+"
    r"build/(?:src/overlays/o(\d+)/overlay_\d+\.c\.o"
    r"|asm/data/overlays/o(\d+)/overlay_\d+\.data\.s\.o)"
)

REF_OUT_RE = re.compile(r"^Overlay\s+(\d+)\s+->\s+\[([^\]]*)\]\s+\((\d+) references?\)")
REF_IN_RE = re.compile(r"^Overlay\s+(\d+)\s+<-\s+\[([^\]]*)\]\s+\((\d+) callers?\)")


def load_json(path):
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def hx(s):
    """Parse a '0x...' string from the atlas into an int."""
    return int(s, 16)


# ---------------------------------------------------------------------------
# JFG side
# ---------------------------------------------------------------------------


def parse_jfg_syms(path):
    """Return {module_num: [(offset, name), ...]} plus main-code symbol set."""
    modules = defaultdict(list)
    main_code = []
    if not os.path.exists(path):
        return modules, main_code
    current = None
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            m = SECTION_RE.match(line.rstrip("\n"))
            if m:
                kind = m.group(2)
                if kind == "Main Code":
                    current = "main"
                elif kind.startswith("Module"):
                    current = int(m.group(3))
                else:
                    current = None  # Data (FFD) / BSS -- not module code
                continue
            if current is None:
                continue
            if current == "main":
                m2 = MAIN_SYM_RE.match(line)
                if m2:
                    main_code.append((int(m2.group(1), 16), m2.group(2)))
                continue
            m2 = SYM_RE.match(line)
            if m2:
                off = int(m2.group(1), 16)
                name = m2.group(2)
                if AUTOEXIT_RE.match(name):
                    continue
                modules[current].append((off, name))
    for k in modules:
        modules[k].sort()
    return modules, main_code


def parse_jfg_map(path):
    """Return {module_num: {"text": n, "data": n, "bss": n}}."""
    sizes = defaultdict(lambda: defaultdict(int))
    if not os.path.exists(path):
        return sizes
    with open(path, encoding="utf-8", errors="replace") as fh:
        for line in fh:
            m = MAP_OBJ_RE.match(line)
            if not m:
                continue
            sec, _addr, size, n1, n2 = m.groups()
            n = int(n1 or n2)
            sizes[n][sec] += int(size, 16)
    return sizes


def parse_jfg_refs(path):
    """Return (out_edges, in_edges): {module: {neighbour: count}}."""
    out_edges = defaultdict(dict)
    in_edges = defaultdict(dict)
    if not os.path.exists(path):
        return out_edges, in_edges
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            line = line.rstrip("\n")
            m = REF_OUT_RE.match(line)
            if m:
                src = int(m.group(1))
                targets = [int(t) for t in m.group(2).split(",") if t.strip()]
                for t in targets:
                    out_edges[src][t] = out_edges[src].get(t, 0) + 1
                continue
            m = REF_IN_RE.match(line)
            if m:
                dst = int(m.group(1))
                sources = [int(t) for t in m.group(2).split(",") if t.strip()]
                for s in sources:
                    in_edges[dst][s] = in_edges[dst].get(s, 0) + 1
    return out_edges, in_edges


def jfg_function_sizes(offsets, text_size):
    """Given sorted (offset, name) pairs and the module's text size, return
    a list of (name, offset, size) using next-offset deltas and the text
    bound for the last one. Offsets/sizes only -- names are JFG's own."""
    out = []
    for i, (off, name) in enumerate(offsets):
        if i + 1 < len(offsets):
            end = offsets[i + 1][0]
        else:
            end = text_size if text_size else off
        size = max(end - off, 0)
        out.append((name, off, size))
    return out


def build_jfg_features(syms_path, map_path, refs_path):
    modules, main_code = parse_jfg_syms(syms_path)
    sizes = parse_jfg_map(map_path)
    out_edges, in_edges = parse_jfg_refs(refs_path)
    main_names = {name for _, name in main_code}

    features = {}
    functions = {}
    for mod, offsets in modules.items():
        sz = sizes.get(mod, {})
        text = sz.get("text", 0)
        data = sz.get("data", 0) + sz.get("rodata", 0)
        bss = sz.get("bss", 0)
        fn_sizes = jfg_function_sizes(offsets, text)
        functions[mod] = fn_sizes
        out_deg = len(out_edges.get(mod, {}))
        in_deg = len(in_edges.get(mod, {}))
        out_rel = sum(out_edges.get(mod, {}).values())
        in_rel = sum(in_edges.get(mod, {}).values())
        features[mod] = {
            "text_size": text,
            "data_size": data,
            "bss_size": bss,
            "function_count": len(offsets),
            "out_degree": out_deg,
            "in_degree": in_deg,
            "out_relocations": out_rel,
            "in_relocations": in_rel,
            "neighbours_out": set(out_edges.get(mod, {})),
            "neighbours_in": set(in_edges.get(mod, {})),
        }
    return features, functions, main_names


# ---------------------------------------------------------------------------
# Mickey side
# ---------------------------------------------------------------------------


def build_mickey_features(atlas):
    modules = atlas["modules"]
    in_edges = defaultdict(set)
    for m in modules:
        for imp in m["imports"]:
            in_edges[imp["overlay"]].add(m["overlay"])

    features = {}
    functions = {}
    for m in modules:
        ovl = m["overlay"]
        text = hx(m["sections"]["text"]["size"])
        data = hx(m["sections"]["data_rodata"]["size"])
        bss = hx(m["bss_size"]) if isinstance(m["bss_size"], str) else m["bss_size"]
        c_entries = [e for e in m["text_ownership"] if e["type"] == "c"]
        asm_entries = [e for e in m["text_ownership"] if e["type"] == "asm"]
        fn_list = [
            (e["source"].rsplit("/", 1)[-1], hx(e["offset"]), hx(e["size"]))
            for e in c_entries
        ]
        out_targets = {imp["overlay"] for imp in m["imports"]}
        out_rel = sum(imp["relocations"] for imp in m["imports"])
        functions[ovl] = fn_list
        features[ovl] = {
            "text_size": text,
            "data_size": data,
            "bss_size": bss,
            "function_count": len(c_entries) + len(asm_entries),
            "matched_function_count": len(c_entries),
            "out_degree": len(out_targets),
            "in_degree": len(in_edges[ovl]),
            "out_relocations": out_rel,
            "in_relocations": m["cross_overlay_inbound_relocations"],
            "neighbours_out": out_targets,
            "neighbours_in": set(in_edges[ovl]),
        }
    return features, functions


# ---------------------------------------------------------------------------
# Scoring
# ---------------------------------------------------------------------------

VECTOR_KEYS = (
    "text_size",
    "data_size",
    "bss_size",
    "function_count",
    "out_degree",
    "in_degree",
    "out_relocations",
    "in_relocations",
)

# Cosine similarity over these log-scaled counts collapses toward 1.0 for
# any pair of small, mostly-empty modules (a handful of near-zero dims that
# happen to point the same way outweighs the one dim that actually differs),
# which is exactly the regime most overlays are in (median text size is a
# few hundred bytes). ratio_similarity avoids that: each feature is scored
# as min/max in [0, 1], so two modules of very different size score low on
# that feature regardless of how many other dims are zero on both sides.


def ratio_similarity(a, b):
    hi, lo = max(a, b), min(a, b)
    if hi == 0:
        return 1.0
    return lo / hi


def degree_shape_similarity(fa, fb):
    """Cheap 'graph shape' term: how similar in/out degree and relocation
    counts are, independent of absolute size. Neighbour *identity* cannot be
    compared directly -- overlay numbers on the two sides are unrelated --
    so this stays a coarse degree-profile match, not a subgraph isomorphism."""
    parts = []
    for a, b in (
        (fa["out_degree"], fb["out_degree"]),
        (fa["in_degree"], fb["in_degree"]),
    ):
        hi, lo = max(a, b), min(a, b)
        parts.append(1.0 if hi == 0 else lo / hi)
    return sum(parts) / len(parts)


def score_pair(mfeat, jfeat):
    size_terms = [
        ratio_similarity(mfeat["text_size"], jfeat["text_size"]),
        ratio_similarity(mfeat["data_size"], jfeat["data_size"]),
        ratio_similarity(mfeat["bss_size"], jfeat["bss_size"]),
    ]
    # text size is the most reliable single signal (it is present and
    # nonzero for nearly every module on both sides); weight it double.
    size_score = (2 * size_terms[0] + size_terms[1] + size_terms[2]) / 4
    fn_score = ratio_similarity(mfeat["function_count"], jfeat["function_count"])
    shape = degree_shape_similarity(mfeat, jfeat)
    return 0.5 * size_score + 0.3 * fn_score + 0.2 * shape


def rank_candidates(m_features, j_features, top_n=3):
    results = {}
    for ovl, mfeat in m_features.items():
        scored = []
        for mod, jfeat in j_features.items():
            s = score_pair(mfeat, jfeat)
            scored.append((s, mod))
        scored.sort(key=lambda t: -t[0])
        results[ovl] = scored[:top_n]
    return results


def confidence_flag(top, mfeat=None):
    """A pair is 'confident' when the best score clears an absolute floor
    AND has a clear margin over the runner-up -- both are needed since a
    small module pool makes small absolute scores common. An all-zero (truly
    empty) Mickey overlay is never confident: ratio_similarity(0, 0) == 1.0
    for every feature, so an empty module trivially scores 1.0 against any
    other near-empty module and that is a degenerate match, not a real one."""
    if mfeat is not None and mfeat.get("text_size", 0) == 0:
        return False
    if len(top) < 2:
        return len(top) == 1 and top[0][0] >= 0.75
    best, second = top[0][0], top[1][0]
    if best < 0.70:
        return False
    if second <= 0:
        return True
    return (best - second) / best >= 0.25


# ---------------------------------------------------------------------------
# Name proposals for confident matches
# ---------------------------------------------------------------------------


def propose_names(m_functions, j_functions, ovl, mod):
    """Line up Mickey's matched (named-by-offset-only, e.g. func_ stand-ins
    are absent here since only matched 'c' entries carry names) functions
    against JFG's module functions by rank order and relative offset/size,
    and propose a name where the shape agrees. Every proposal is Tier D
    (structural) unless flagged otherwise by the caller -- this function
    does not have byte evidence and must not claim Tier B on its own."""
    mfns = m_functions.get(ovl, [])
    jfns = j_functions.get(mod, [])
    proposals = []
    if not mfns or not jfns:
        return proposals
    m_sorted = sorted(mfns, key=lambda t: t[1])
    j_sorted = sorted(jfns, key=lambda t: t[1])
    # Rank-order alignment by position, since neither list is byte-comparable
    # across a revision gap. Both are pre-existing lists (Mickey's atlas
    # source names, JFG's published names): only the pairing is new here.
    n = min(len(m_sorted), len(j_sorted))
    for i in range(n):
        mname, moff, msize = m_sorted[i]
        jname, joff, jsize = j_sorted[i]
        if msize == 0 or jsize == 0:
            continue
        hi, lo = max(msize, jsize), min(msize, jsize)
        size_ratio = lo / hi
        proposals.append(
            {
                "mickey_source": mname,
                "mickey_offset": hex(moff),
                "mickey_size": hex(msize),
                "jfg_name": jname,
                "jfg_offset": hex(joff),
                "jfg_size": hex(jsize),
                "size_ratio": round(size_ratio, 3),
                "evidence_tier": "D",
                "note": (
                    "rank-order position + size agreement only; not a byte "
                    "or call-graph claim"
                ),
            }
        )
    return proposals


# ---------------------------------------------------------------------------
# Self-test: JFG-us vs JFG-kiosk should recover ~identity
# ---------------------------------------------------------------------------


def run_self_test():
    us_feat, us_fns, _ = build_jfg_features(JFG_SYMS_US, JFG_MAP, JFG_REFS)
    kiosk_modules, _ = parse_jfg_syms(JFG_SYMS_KIOSK)
    if not us_feat or not kiosk_modules:
        return {
            "ran": False,
            "reason": "JFG reference files not found at JFG_ROOT="
            + JFG_ROOT,
        }
    # Kiosk doesn't ship its own map/refs in this checkout; approximate its
    # sizes from symbol-offset deltas within each module's own text run
    # (last symbol's own module has no explicit text bound, so its final
    # function's size is left at 0 and excluded from that module's vector --
    # this only affects the coarse feature vector, not the recovery count).
    kiosk_feat = {}
    kiosk_fns = {}
    for mod, offsets in kiosk_modules.items():
        approx_text = offsets[-1][0] if offsets else 0
        fn_sizes = jfg_function_sizes(offsets, approx_text)
        kiosk_fns[mod] = fn_sizes
        kiosk_feat[mod] = {
            "text_size": approx_text,
            "data_size": 0,
            "bss_size": 0,
            "function_count": len(offsets),
            "out_degree": 0,
            "in_degree": 0,
            "out_relocations": 0,
            "in_relocations": 0,
            "neighbours_out": set(),
            "neighbours_in": set(),
        }

    ranked = rank_candidates(us_feat, kiosk_feat, top_n=3)
    total = len(ranked)
    top1_correct = 0
    top3_correct = 0
    confident = 0
    confident_correct = 0
    for mod, top in ranked.items():
        cands = [c[1] for c in top]
        if cands and cands[0] == mod:
            top1_correct += 1
        if mod in cands:
            top3_correct += 1
        if confidence_flag(top, us_feat.get(mod)):
            confident += 1
            if top and top[0][1] == mod:
                confident_correct += 1

    return {
        "ran": True,
        "pairs_tested": total,
        "top1_accuracy": round(top1_correct / total, 3) if total else 0,
        "top3_accuracy": round(top3_correct / total, 3) if total else 0,
        "confident_pairs": confident,
        "confident_pairs_correct": confident_correct,
        "confident_precision": round(confident_correct / confident, 3)
        if confident
        else None,
        "note": (
            "JFG-us vs JFG-kiosk is the SAME game at two revisions, so this "
            "upper-bounds what a size/count/degree profile can recover; the "
            "Mickey<->JFG problem is strictly harder (different game, "
            "different revision, resident-vs-overlay boundary moved)."
        ),
    }


def run_anchor_check(m_features, j_features):
    out = {}
    for ovl, anchor in KNOWN_ANCHORS.items():
        mod = anchor["jfg_module"]
        mfeat = m_features.get(ovl)
        jfeat = j_features.get(mod)
        if mfeat is None or jfeat is None:
            out[ovl] = {"symbol": anchor["symbol"], "jfg_module": mod, "ran": False}
            continue
        ranked_full = rank_candidates(
            {ovl: mfeat}, j_features, top_n=len(j_features)
        )[ovl]
        rank = next((i for i, (_, m) in enumerate(ranked_full) if m == mod), None)
        out[ovl] = {
            "symbol": anchor["symbol"],
            "jfg_module": mod,
            "score": next((s for s, m in ranked_full if m == mod), None),
            "rank_among_all_157": rank + 1 if rank is not None else None,
            "top1_score": ranked_full[0][0],
            "top1_module": ranked_full[0][1],
            "mickey_text_size": mfeat["text_size"],
            "jfg_text_size": jfeat["text_size"],
        }
    out["unanchorable"] = UNANCHORABLE
    return out


# ---------------------------------------------------------------------------
# Report assembly
# ---------------------------------------------------------------------------


def build_report():
    atlas = load_json(ATLAS)
    m_features, m_functions = build_mickey_features(atlas)
    j_features, j_functions, main_names = build_jfg_features(
        JFG_SYMS_US, JFG_MAP, JFG_REFS
    )

    jfg_available = bool(j_features)
    ranked = rank_candidates(m_features, j_features) if jfg_available else {}

    overlays_out = []
    confident_count = 0
    for ovl in sorted(m_features):
        top = ranked.get(ovl, [])
        confident = confidence_flag(top, m_features[ovl]) if top else False
        if confident:
            confident_count += 1
        candidates = []
        for score, mod in top:
            entry = {
                "jfg_module": mod,
                "score": round(score, 4),
                "jfg_text_size": j_features[mod]["text_size"],
                "jfg_function_count": j_features[mod]["function_count"],
            }
            if confident and (score, mod) == top[0]:
                entry["name_proposals"] = propose_names(
                    m_functions, j_functions, ovl, mod
                )
            candidates.append(entry)
        overlays_out.append(
            {
                "overlay": ovl,
                "mickey_text_size": m_features[ovl]["text_size"],
                "mickey_data_size": m_features[ovl]["data_size"],
                "mickey_bss_size": m_features[ovl]["bss_size"],
                "mickey_function_count": m_features[ovl]["function_count"],
                "mickey_matched_function_count": m_features[ovl][
                    "matched_function_count"
                ],
                "out_degree": m_features[ovl]["out_degree"],
                "in_degree": m_features[ovl]["in_degree"],
                "confident": confident,
                "candidates": candidates,
            }
        )

    anchors = run_anchor_check(m_features, j_features) if jfg_available else {}
    self_test = run_self_test()

    report = {
        "schema_version": 1,
        "generated_by": "tools/overlay_graph_match.py",
        "source": {
            "mickey_atlas": os.path.relpath(ATLAS, REPO),
            "jfg_root": JFG_ROOT,
            "jfg_root_available": jfg_available,
        },
        "method": (
            "Cosine similarity over log(text/data/bss size, function count, "
            "in/out degree, in/out cross-overlay relocation totals), blended "
            "0.6/0.2/0.2 with a degree-profile shape term and a function-count "
            "ratio term. No neighbour-identity subgraph matching -- overlay "
            "numbers are not comparable across the two games."
        ),
        "totals": {
            "mickey_overlays": len(m_features),
            "jfg_modules_available": len(j_features),
            "confident_matches": confident_count,
        },
        "calibration": {
            "known_anchors": anchors,
            "self_test_jfg_us_vs_kiosk": self_test,
        },
        "overlays": overlays_out,
    }
    return report


def summarize(report):
    t = report["totals"]
    print(
        f"{t['mickey_overlays']} Mickey overlays, "
        f"{t['jfg_modules_available']} JFG modules available, "
        f"{t['confident_matches']} confident matches"
    )
    st = report["calibration"]["self_test_jfg_us_vs_kiosk"]
    if st.get("ran"):
        print(
            f"self-test (JFG us vs kiosk): top1={st['top1_accuracy']} "
            f"top3={st['top3_accuracy']} "
            f"confident_precision={st['confident_precision']}"
        )
    else:
        print(f"self-test skipped: {st.get('reason')}")
    for ovl, a in report["calibration"]["known_anchors"].items():
        if ovl == "unanchorable":
            continue
        print(f"anchor overlay {ovl} ({a['symbol']}) -> module {a['jfg_module']}: "
              f"rank {a.get('rank_among_all_157')} of 157, "
              f"top1 is module {a.get('top1_module')}")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--self-test", action="store_true")
    ap.add_argument("--overlay", type=int)
    args = ap.parse_args()

    if args.self_test:
        st = run_self_test()
        print(json.dumps(st, indent=2))
        return 0

    report = build_report()

    if args.overlay is not None:
        row = next(
            (o for o in report["overlays"] if o["overlay"] == args.overlay), None
        )
        print(json.dumps(row, indent=2))
        return 0

    if args.write:
        with open(REPORT, "w", encoding="utf-8") as fh:
            json.dump(report, fh, indent=2)
            fh.write("\n")
        print(f"wrote {os.path.relpath(REPORT, REPO)}")
        summarize(report)
        return 0

    if args.check:
        if not os.path.exists(REPORT):
            print("missing config/overlay-graph.us.json; run --write", file=sys.stderr)
            return 1
        on_disk = load_json(REPORT)
        # Round-trip the freshly built report through JSON before comparing:
        # build_report() uses int overlay numbers as dict keys internally
        # (e.g. calibration.known_anchors), but JSON object keys are always
        # strings, so on_disk already has them as strings. Comparing the raw
        # Python dict against on_disk would report every re-run as stale.
        fresh = json.loads(json.dumps(build_report()))
        # Compare everything except nothing -- both are fully deterministic
        # given the same inputs.
        if on_disk != fresh:
            print("config/overlay-graph.us.json is stale; run --write", file=sys.stderr)
            return 1
        print("config/overlay-graph.us.json is up to date")
        return 0

    summarize(report)
    return 0


if __name__ == "__main__":
    sys.exit(main())
